[pytest]
addopts = -v
testpaths = tests
markers =
    print: mostly focus on printing output
    print_scores: check scores
    integration: mark test as integration test
    unit: mark test as unit test
    base: mark tests as related to base functionality
    fast: mark tests as computationaly fast
    slow: mark tests as computationaly slow
    init: mark tests as initalization
    e2e: mark tests as end to end test
    test_this: this will execute only test we want

pythonpath = .
